server:
  port: 8080
  servlet: 
     session: 
        cookie:
           http-only: false
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  main:
    allow-bean-definition-overriding: true
  data-source1:
    name: dataSource1
    url: jdbc:sqlite:iotdbui.db
    useSSL: false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters:
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  messages:
    basename: messages/message
    encoding: utf-8
iotdbui:
   frontend: 
   email:
     port: 465
     host: 
     username: 
     password: 