version: "3.7"

services:
  backend:
    build: .
    restart: always
    volumes:
    - ./iotdbui.db:/iotdbui.db

  frontend:
    image: nginx
    restart: always
    ports: 
    - 8040:8040
    volumes:
    - ./front/dist:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend 
